CREATE TABLE USUARIO(
  USUARIO_ID NUMERIC(10,2) NOT NULL PRIMARY KEY,
  USUARIO VARCHAR2(20) NOT NULL UNIQUE,
  CLAVE VARCHAR2(60) NOT NULL ,
  NOMBRE VARCHAR2(180),
  ESTADO CHAR(1) DEFAULT 1
);

CREATE OR REPLACE 
PACKAGE PKG_USUARIO AS 

    PROCEDURE SP_VALIDAR_ACCESO(
      P_CURSOR  OUT SYS_REFCURSOR,
      P_USUARIO IN  USUARIO.USUARIO%TYPE,
      P_CLAVE   IN  USUARIO.CLAVE%TYPE
  ); 
  
END PKG_USUARIO;

CREATE OR REPLACE
PACKAGE BODY PKG_USUARIO AS

  PROCEDURE SP_VALIDAR_ACCESO(
      P_CURSOR  OUT SYS_REFCURSOR,
      P_USUARIO IN  USUARIO.USUARIO%TYPE,
      P_CLAVE   IN  USUARIO.CLAVE%TYPE
  ) AS
  BEGIN
    OPEN 
      P_CURSOR
    FOR
        SELECT
            USUARIO_ID,
            USUARIO,
            NOMBRE
        FROM
            USUARIO
        WHERE
                upper(USUARIO)   =   upper(P_USUARIO)
            AND CLAVE            =   P_CLAVE;

  END SP_VALIDAR_ACCESO;

END PKG_USUARIO;