CREATE TABLE CLIENTE(
  CLIENTE_ID NUMERIC(10,2) NOT NULL PRIMARY KEY,
  RAZON_SOCIAL VARCHAR2(120) NOT NULL UNIQUE,
  RUC CHAR(11)NOT NULL UNIQUE,
  DIRECCION VARCHAR2(180),
  ESTADO CHAR(1) DEFAULT 1
);

CREATE TABLE VEHICULO(
  VEHICULO_ID NUMERIC(10,2) NOT NULL PRIMARY KEY,
  PLACA CHAR(7) NOT NULL UNIQUE,
  ANO CHAR(4)NOT NULL,
  MODELO VARCHAR2(180),
  ESTADO CHAR(1) DEFAULT 1
);