-- MySQL Script generated by MySQL Workbench
-- 06/29/15 17:24:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_futurama
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_futurama` ;

-- -----------------------------------------------------
-- Schema db_futurama
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_futurama` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_futurama` ;

-- -----------------------------------------------------
-- Table `db_futurama`.`tb_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_clientes` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_clientes` (
  `numIdentificacion_clie` CHAR(8) NOT NULL,
  `nom_clie` VARCHAR(45) NULL DEFAULT NULL,
  `apePat_clie` VARCHAR(45) NULL DEFAULT NULL,
  `apeMat_clie` VARCHAR(45) NULL DEFAULT NULL,
  `dirrec_clie` VARCHAR(45) NULL DEFAULT NULL,
  `fechaNac_clie` DATE NULL DEFAULT NULL,
  `correo_clie` VARCHAR(45) NULL DEFAULT NULL,
  `numTrabajo_clie` INT NULL DEFAULT NULL,
  `numCel_clie` INT NULL DEFAULT NULL,
  `numTelfijo_clie` INT NULL DEFAULT NULL,
  `distrito_clie` VARCHAR(45) NULL DEFAULT NULL,
  `provincia_clie` VARCHAR(45) NULL DEFAULT NULL,
  `departamento_clie` VARCHAR(45) NULL DEFAULT NULL,
  `estado_clie` VARCHAR(45) NULL DEFAULT 'Disponible',
  `edad_clie` INT NULL DEFAULT NULL,
  `tipohuesped_clie` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`numIdentificacion_clie`),
  UNIQUE INDEX `correo_clie_UNIQUE` (`correo_clie` ASC),
  UNIQUE INDEX `numTrabajo_clie_UNIQUE` (`numTrabajo_clie` ASC),
  UNIQUE INDEX `numCel_clie_UNIQUE` (`numCel_clie` ASC),
  UNIQUE INDEX `numTelfijo_clie_UNIQUE` (`numTelfijo_clie` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_estado` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_estado` (
  `cod_estado` INT NOT NULL AUTO_INCREMENT,
  `tipo_estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_motivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_motivo` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_motivo` (
  `cod_motivo` INT NOT NULL AUTO_INCREMENT,
  `nom_motivo` VARCHAR(45) NULL DEFAULT NULL,
  `cod_estado` INT NOT NULL,
  PRIMARY KEY (`cod_motivo`),
  INDEX `fk_tb_motivo_tb_estado1_idx` (`cod_estado` ASC),
  CONSTRAINT `fk_tb_motivo_tb_estado1`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `db_futurama`.`tb_estado` (`cod_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_llamada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_llamada` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_llamada` (
  `cod_llamada` INT NOT NULL AUTO_INCREMENT,
  `num_llamada` INT NULL DEFAULT NULL,
  `obs_llamada` VARCHAR(100) NULL DEFAULT NULL,
  `cod_motivo` INT NOT NULL,
  `numIdentificacion_clie` CHAR(8) NOT NULL,
  PRIMARY KEY (`cod_llamada`),
  INDEX `fk_tb_llamada_tb_motivo1_idx` (`cod_motivo` ASC),
  INDEX `fk_tb_llamada_tb_clientes1_idx` (`numIdentificacion_clie` ASC),
  UNIQUE INDEX `num_llamada_UNIQUE` (`num_llamada` ASC),
  CONSTRAINT `fk_tb_llamada_tb_motivo1`
    FOREIGN KEY (`cod_motivo`)
    REFERENCES `db_futurama`.`tb_motivo` (`cod_motivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_llamada_tb_clientes1`
    FOREIGN KEY (`numIdentificacion_clie`)
    REFERENCES `db_futurama`.`tb_clientes` (`numIdentificacion_clie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_usuario` (
  `clave` CHAR(6) NOT NULL,
  `usuario` CHAR(6) NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_asesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_asesor` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_asesor` (
  `cod_ases` INT NOT NULL AUTO_INCREMENT,
  `num_identidad_ases` INT NULL DEFAULT NULL,
  `nom_ases` VARCHAR(45) NULL DEFAULT NULL,
  `apePat_ases` VARCHAR(45) NULL DEFAULT NULL,
  `apeMat_ases` VARCHAR(45) NULL DEFAULT NULL,
  `correo_ases` VARCHAR(45) NULL DEFAULT NULL,
  `num_telefono_ases` INT NULL DEFAULT NULL,
  `ref_telefono_ases` INT NULL DEFAULT NULL,
  `dirrec_ases` VARCHAR(100) NULL,
  `fechaNac_ases` DATE NULL DEFAULT NULL,
  `distrito_ases` VARCHAR(45) NULL DEFAULT NULL,
  `provincia_ases` VARCHAR(45) NULL DEFAULT NULL,
  `departamento_ases` VARCHAR(45) NULL DEFAULT NULL,
  `estado_ases` VARCHAR(45) NULL DEFAULT 'Dispinible',
  `cod_llamada` INT NOT NULL,
  `usuario` CHAR(6) NOT NULL,
  PRIMARY KEY (`cod_ases`),
  INDEX `fk_tb_asesor_tb_llamada1_idx` (`cod_llamada` ASC),
  INDEX `fk_tb_asesor_tb_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_tb_asesor_tb_llamada1`
    FOREIGN KEY (`cod_llamada`)
    REFERENCES `db_futurama`.`tb_llamada` (`cod_llamada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_asesor_tb_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `db_futurama`.`tb_usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_hotel` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_hotel` (
  `cod_hotel` INT NOT NULL AUTO_INCREMENT,
  `nom_hotel` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_hotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_campaña`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_campaña` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_campaña` (
  `cod_camp` INT NOT NULL AUTO_INCREMENT,
  `nom_camp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_camp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_pack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_pack` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_pack` (
  `cod_pack` INT NOT NULL AUTO_INCREMENT,
  `nom_pack` VARCHAR(45) NULL DEFAULT NULL,
  `pretotal_pack` FLOAT NULL,
  `cod_hotel` INT NOT NULL,
  `cod_camp` INT NOT NULL,
  PRIMARY KEY (`cod_pack`),
  INDEX `fk_tb_pack_tb_hotel1_idx` (`cod_hotel` ASC),
  INDEX `fk_tb_pack_tb_campaña1_idx` (`cod_camp` ASC),
  CONSTRAINT `fk_tb_pack_tb_hotel1`
    FOREIGN KEY (`cod_hotel`)
    REFERENCES `db_futurama`.`tb_hotel` (`cod_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pack_tb_campaña1`
    FOREIGN KEY (`cod_camp`)
    REFERENCES `db_futurama`.`tb_campaña` (`cod_camp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_habitacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_habitacion` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_habitacion` (
  `cod_hab` INT NOT NULL AUTO_INCREMENT,
  `nom_hab` VARCHAR(45) NULL DEFAULT NULL,
  `preSoles_hab` FLOAT NULL DEFAULT NULL,
  `preDolares_hab` FLOAT NULL,
  `naSoles_hab` FLOAT NULL DEFAULT NULL,
  `naDolares_hab` FLOAT NULL DEFAULT NULL,
  `cod_hotel` INT NOT NULL,
  `pretotal_hab` FLOAT NULL,
  PRIMARY KEY (`cod_hab`),
  INDEX `fk_tb_habitacion_tb_hotel1_idx` (`cod_hotel` ASC),
  CONSTRAINT `fk_tb_habitacion_tb_hotel1`
    FOREIGN KEY (`cod_hotel`)
    REFERENCES `db_futurama`.`tb_hotel` (`cod_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_ticket` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_ticket` (
  `cod_tick` INT NOT NULL AUTO_INCREMENT,
  `fecha_tick` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`cod_tick`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_ventas` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_ventas` (
  `cod_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATE NULL,
  `obser_venta` VARCHAR(45) NULL DEFAULT NULL,
  `cod_tick` INT NOT NULL,
  `cod_ases` INT NOT NULL,
  PRIMARY KEY (`cod_venta`),
  INDEX `fk_tb_ventas_tb_ticket1_idx` (`cod_tick` ASC),
  INDEX `fk_tb_ventas_tb_asesor1_idx` (`cod_ases` ASC),
  CONSTRAINT `fk_tb_ventas_tb_ticket1`
    FOREIGN KEY (`cod_tick`)
    REFERENCES `db_futurama`.`tb_ticket` (`cod_tick`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_ventas_tb_asesor1`
    FOREIGN KEY (`cod_ases`)
    REFERENCES `db_futurama`.`tb_asesor` (`cod_ases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_departamento` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_departamento` (
  `cod_dpt` CHAR(5) NOT NULL,
  `desc_dpt` VARCHAR(100) NULL,
  PRIMARY KEY (`cod_dpt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_provincia` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_provincia` (
  `cod_prov` CHAR(5) NOT NULL,
  `desc_prov` VARCHAR(100) NULL,
  `cod_dpt` CHAR(5) NOT NULL,
  PRIMARY KEY (`cod_prov`, `cod_dpt`),
  INDEX `fk_tb_provincia_tb_departamento1_idx` (`cod_dpt` ASC),
  CONSTRAINT `fk_tb_provincia_tb_departamento1`
    FOREIGN KEY (`cod_dpt`)
    REFERENCES `db_futurama`.`tb_departamento` (`cod_dpt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_distrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_futurama`.`tb_distrito` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_distrito` (
  `cod_dist` CHAR(5) NOT NULL,
  `desc_dist` VARCHAR(45) NULL,
  `cod_prov` CHAR(5) NOT NULL,
  `cod_dpt` CHAR(5) NOT NULL,
  PRIMARY KEY (`cod_dist`, `cod_prov`, `cod_dpt`),
  INDEX `fk_tb_distrito_tb_provincia1_idx` (`cod_prov` ASC, `cod_dpt` ASC),
  CONSTRAINT `fk_tb_distrito_tb_provincia1`
    FOREIGN KEY (`cod_prov` , `cod_dpt`)
    REFERENCES `db_futurama`.`tb_provincia` (`cod_prov` , `cod_dpt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_futurama`.`tb_detalle_ventas`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `db_futurama`.`tb_detalle_ventas` ;

CREATE TABLE IF NOT EXISTS `db_futurama`.`tb_detalle_ventas` (
  `cod_venta` INT NOT NULL,
  `cod_pack` INT NOT NULL,
  `cantidad_venta` INT NULL,
  `precio_total_venta` FLOAT NULL,
  PRIMARY KEY (`cod_venta`, `cod_pack`),
  INDEX `fk_tb_ventas_has_tb_pack_tb_pack1_idx` (`cod_pack` ASC),
  INDEX `fk_tb_ventas_has_tb_pack_tb_ventas1_idx` (`cod_venta` ASC),
  CONSTRAINT `fk_tb_ventas_has_tb_pack_tb_ventas1`
    FOREIGN KEY (`cod_venta`)
    REFERENCES `db_futurama`.`tb_ventas` (`cod_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_ventas_has_tb_pack_tb_pack1`
    FOREIGN KEY (`cod_pack`)
    REFERENCES `db_futurama`.`tb_pack` (`cod_pack`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ------------------CONSULTAS-------------------------------------


select * from tb_usuario;


use db_futurama;

select v.fecha_venta, v.obser_venta, concat('',a.nom_ases ,'\n',a.apePat_ases,'\n',a.apeMat_ases)as  'Nombre Asesor' ,p.nom_pack,c.nom_camp,de.precio_total_venta
from tb_ventas v 
inner join tb_asesor a
on a.cod_ases = v.cod_ases
inner join tb_detalle_ventas de
on v.cod_venta = de.cod_venta
inner join tb_pack p
on de.cod_pack = p.cod_pack
inner join tb_campaña c
on p.cod_camp = c.cod_camp;


/* habitacion por hoteles */
select h.cod_hab,h.nom_hab, ho.cod_hotel,ho.nom_hotel From tb_habitacion h 
inner join tb_hotel ho 
on  h.cod_hotel=ho.cod_hotel; 


Update tb_clientes set nom_clie='Alvaro',apePat_clie='Diego', apeMat_clie='agui',dirrec_clie='caly',fechaNac_clie='1992-12-02', correo_clie='die.com',numTrabajo_clie=1343,numCel_clie=123245,numTelfijo_clie=343411, distrito_clie='San luis', provincia_clie='lima',departamento_clie='lima' where numIdentificacion_clie = '21312323';
create view lista_cli as
select numIdentificacion_clie,nom_clie,apePat_clie,apeMat_clie,correo_clie,numCel_clie, numTelfijo_clie,estado_clie from tb_clientes;
/* distritos Con la letra S*/
select * From tb_distrito where desc_dist like 'S%';
/*CAntidad de distritos*/
select count(cod_dist) as'Cantidad de Distritos' from tb_distrito;


/*inserciones de usuarios*/

insert into tb_usuario values('123456','AD0001','Administrador');
insert into tb_usuario values('alvaro','A00002','Asesor');
insert into tb_usuario values('270392','J00003','Jefe Ventas');
insert into tb_usuario values('111111','A00004','Asesor');
select usuario,clave from tb_usuario where usuario=1 and clave=1;

select * from tb_usuario;
/*inserciones de estado*/
INSERT INTO `db_futurama`.`tb_estado` (`cod_estado`, `tipo_estado`) VALUES ('1', 'Disponible');
INSERT INTO `db_futurama`.`tb_estado` (`cod_estado`, `tipo_estado`) VALUES ('2', 'No disponible');

/*  inserciones hoteles despues se ejecuta habitacion*/ 
INSERT INTO `db_futurama`.`tb_hotel` (`cod_hotel`, `nom_hotel`) VALUES ('00001', 'O\'Bryan');
INSERT INTO `db_futurama`.`tb_hotel` (`cod_hotel`, `nom_hotel`) VALUES ('00002', 'Sheraton');
INSERT INTO `db_futurama`.`tb_hotel` (`cod_hotel`, `nom_hotel`) VALUES ('00003', 'Marrior');

/*  inserciones de Campañas*/
INSERT INTO `db_futurama`.`tb_campaña` (`cod_camp`, `nom_camp`) VALUES ('1', 'Dia de la Madre');
select * from tb_campaña;

/*inserciones de clientes */
select * from tb_clientes;
INSERT INTO `db_futurama`.`tb_clientes`(`numIdentificacion_clie`,`nom_clie`, `apePat_clie`, `apeMat_clie`, `dirrec_clie`,`fechaNac_clie`, `correo_clie`,`numTrabajo_clie`, `numCel_clie`, `numTelfijo_clie`, `tipohuesped_clie`, `edad_clie`, `distrito_clie`, `provincia_clie`,`departamento_clie`) VALUES ('47082901', 'Susan', 'Aracelli', 'Paucar', 'A.H pedro Los mz A lt 3', '1993/04/02','susan@gamil.com', 4353860, 986809252, 4373715,  'Responsable',21,'San Juan Miraflores','Lima','Lima');
INSERT INTO `db_futurama`.`tb_clientes` (`numIdentificacion_clie`,  `nom_clie`, `apePat_clie`, `apeMat_clie`, `dirrec_clie`, `fechaNac_clie`, `correo_clie`, `edad_clie`) VALUES ('47088490', 'Teresa', 'Paucar', 'SAvala', 'A.H pedro Los mz A lt 3', '1993-04-02', 'su@gamil.com', '21');
INSERT INTO `db_futurama`.`tb_clientes` (`numIdentificacion_clie`, `nom_clie`, `apePat_clie`, `apeMat_clie`, `correo_clie`, `numCel_clie`, `numTelfijo_clie`) VALUES ('45566767', 'Diego', 'Zapata', 'Jen', 'Diego@gmail.com', '986890594', '47769999');


/*inserciones de motivos*/

INSERT INTO `db_futurama`.`tb_motivo` (`cod_motivo`, `nom_motivo`,`cod_estado`) VALUES ('1', 'no constesta','1');
INSERT INTO `db_futurama`.`tb_motivo` (`cod_motivo`, `nom_motivo`,`cod_estado`) VALUES ('2', 'ocupado','1');
INSERT INTO `db_futurama`.`tb_motivo` (`cod_motivo`, `nom_motivo`,`cod_estado`) VALUES ('3', 'contesto','1');
INSERT INTO `db_futurama`.`tb_motivo` (`cod_motivo`, `nom_motivo`,`cod_estado`) VALUES ('4', 'cancelacion de numero','2');
INSERT INTO `db_futurama`.`tb_motivo` (`cod_motivo`, `nom_motivo`,`cod_estado`) VALUES ('5', 'numero no existe','2');
INSERT INTO `db_futurama`.`tb_motivo` (`cod_motivo`, `nom_motivo`,`cod_estado`) VALUES ('6', 'numero equivocado','2');

/*inseciones de llamadas */
INSERT INTO `db_futurama`.`tb_llamada` (`cod_llamada`, `num_llamada`, `obs_llamada`, `cod_motivo`,`numIdentificacion_clie`) VALUES ('1', 4353860, 'llamada fue factible', '3','47082901');


/*inserciones de ticket de atencion */

INSERT INTO `db_futurama`.`tb_ticket` (`cod_tick`, `fecha_tick`) VALUES ('1', '1992/02/27');
INSERT INTO `db_futurama`.`tb_ticket` (`cod_tick`, `fecha_tick`) VALUES ('2', '1995/09/30');

/*aSesor*/
select * from tb_asesor;
INSERT INTO `db_futurama`.`tb_asesor` (`cod_ases`,  `num_identidad_ases`, `nom_ases`, `apePat_ases`, `apeMat_ases`, `correo_ases`,  `num_telefono_ases`, `ref_telefono_ases`, `dirrec_ases`, `fechaNac_ases`, `distrito_ases`, `provincia_ases`, `departamento_ases`, `cod_llamada`,`usuario`) VALUES ('1', '47082903', 'Alvaro', 'Aguinaga', 'Delagdo', 'Alvaro_9218@hotmail.com',  '4353860', '986809252', 'Calle San Miguel 488', '1992/03/27', 'SAN LUIS', 'LIMA', 'LIMA', '1','A00002');
INSERT INTO `db_futurama`.`tb_asesor` (`cod_ases`, `num_identidad_ases`, `nom_ases`, `apePat_ases`, `apeMat_ases`, `correo_ases`, `num_telefono_ases`, `ref_telefono_ases`, `dirrec_ases`, `fechaNac_ases`, `distrito_ases`, `provincia_ases`, `departamento_ases`, `cod_llamada`, `usuario`, `estado_ases`) VALUES ('2', '43243243', 'maruja', 'delgado', 'vasquez', 'maruja@hotmail.com', '2341234', '984534232', 'calle san milgr', '1992-03-12', 'san luis', 'lima', 'lima', '1', 'A00004', 'Indispnible');
insert INTO `db_futurama`.`tb_asesor` (`cod_ases`,  `num_identidad_ases`, `nom_ases`, `apePat_ases`, `apeMat_ases`, `correo_ases`, `num_telefono_ases`, `ref_telefono_ases`, `dirrec_ases`, `fechaNac_ases`, `distrito_ases`, `provincia_ases`, `departamento_ases`, `cod_llamada`, `usuario`) VALUES ('3', '12121121', 'andre', 'paucar', 'usca', 'andre@hotmail.com', '3454906', '985783241', 'calle san miguel 488', '1993-05-11', 'san luis', 'lima', 'lims', '1', 'AD0001');


/*insercione  de Ventas */
INSERT INTO `db_futurama`.`tb_ventas` (`cod_venta`, `fecha_venta`, `obser_venta`, `cod_tick`,`cod_ases`) VALUES ('1', '1992/03/27', 'venta con exito ', '1','1');
select * from tb_ventas;

/* inserciones de pack turisticos */

INSERT INTO `db_futurama`.`tb_pack` (`cod_pack`, `nom_pack`, `pretotal_pack`, `cod_hotel`,`cod_camp`) VALUES ('1', 'Viajes Unicos', '287', '1','1');
INSERT INTO `db_futurama`.`tb_pack` (`cod_pack`, `nom_pack`, `pretotal_pack`, `cod_hotel`,`cod_camp`) VALUES ('2', 'Mama Viajes', '356', '2','1');
INSERT INTO `db_futurama`.`tb_pack` (`cod_pack`, `nom_pack`, `pretotal_pack`, `cod_hotel`,`cod_camp`) VALUES ('3', 'Regalale A Mama', '324', '3','1');


/*  insercciones Habitaciones*/ 
INSERT INTO `db_futurama`.`tb_habitacion` (`cod_hab`, `nom_hab`, `preSoles_hab`, `preDolares_hab`, `naSoles_hab`, `naDolares_hab`, `cod_hotel`) VALUES ('00001', 'suit001', '155.00', '69.00', '55', '23', '00001');


/*detalle de venta */
INSERT INTO `db_futurama`.`tb_detalle_ventas` (`cod_venta`, `cod_pack`, `cantidad_venta`, `precio_total_venta`) VALUES ('1', '1', '1', '17000');
select * from tb_detalle_ventas;


select * from tb_llamada;

INSERT INTO tb_departamento(cod_dpt,desc_dpt) VALUES ('PA001','LIMA');
INSERT INTO tb_departamento(cod_dpt,desc_dpt) VALUES ('PA002','CALLAO');


INSERT INTO tb_provincia(cod_dpt,cod_prov,desc_prov) VALUES ('PA001','PR001','LIMA');
INSERT INTO tb_provincia(cod_dpt,cod_prov,desc_prov)VALUES ('PA002','PR002','CALLAO');


INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI001','PA001','PR001','SAN ISIDRO');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI002','PA001','PR001','SAN JUAN DE MIRAFLORES');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI003','PA001','PR001','SANTA ANITA');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI004','PA001','PR001','INDEPENDENCIA');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI005','PA001','PR001','COMAS');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI006','PA001','PR001','LINCE');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI007','PA001','PR001','SAN MIGUEL');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI008','PA001','PR001','SURCO');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI009','PA001','PR001','MIRAFLORES');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI010','PA001','PR001','SURQUILLO');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI011','PA001','PR001','ATE');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI012','PA001','PR001','VENTANILLA');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI013','PA001','PR001','PUENTE PIEDRA');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI014','PA001','PR001','LOS OLIVOS');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI015','PA001','PR001','SAN MARTIN');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI016','PA001','PR001','LIMA');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI017','PA001','PR001','SURQUILLO');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI018','PA001','PR001','RIMAC');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI019','PA001','PR001','SAN JUAN DE LURIGANCHO');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI020','PA001','PR001','AGUSTINO');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI021','PA001','PR001','SAN BORJA');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI022','PA001','PR001','CHORRILLOS');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI023','PA001','PR001','VILLA MARIA TRIUNFO');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI024','PA001','PR001','VILLA EL SALVADOR');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI025','PA001','PR001','BREÑA');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI026','PA001','PR001','PUEBLO LIBRE');
INSERT INTO tb_distrito(COD_DIST,COD_DPT,COD_PROV,DESC_DIST) VALUES ('DI027','PA001','PR001','SAN LUIS');

select * from tb_distrito;

