# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-spring
  template:
    metadata:
      labels:
        app: app-spring
    spec:
      containers:
        - name: app-spring
          image: gcr.io/jalvarova/app-spring:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
            - name: MINIO_HOST
              value: minio
            - name: MINIO_SECURED
              value: "false"
            - name: MINIO_PORT
              value: "9000"
          imagePullPolicy: Always
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: app-spring
spec:
  selector:
    app: app-spring
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
